# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.operational_webhook_endpoint_update_dto import OperationalWebhookEndpointUpdateDto

class TestOperationalWebhookEndpointUpdateDto(unittest.TestCase):
    """OperationalWebhookEndpointUpdateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OperationalWebhookEndpointUpdateDto:
        """Test OperationalWebhookEndpointUpdateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OperationalWebhookEndpointUpdateDto`
        """
        model = OperationalWebhookEndpointUpdateDto()
        if include_optional:
            return OperationalWebhookEndpointUpdateDto(
                url = 'https://example.com/new-webhook/',
                description = 'Updated monitoring endpoint',
                disabled = True,
                filter_types = [message.attempt.failing, message.attempt.exhausted, endpoint.disabled],
                metadata = {environment=staging},
                throttle_rate = 10,
                uid = 'monitoring-updated-endpoint'
            )
        else:
            return OperationalWebhookEndpointUpdateDto(
                url = 'https://example.com/new-webhook/',
        )
        """

    def testOperationalWebhookEndpointUpdateDto(self):
        """Test OperationalWebhookEndpointUpdateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
