# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.resolved_addon import ResolvedAddon

class TestResolvedAddon(unittest.TestCase):
    """ResolvedAddon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResolvedAddon:
        """Test ResolvedAddon
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResolvedAddon`
        """
        model = ResolvedAddon()
        if include_optional:
            return ResolvedAddon(
                product_id = 'prod_addon_123',
                name = 'Extra Seats add-on',
                image_url = solifyn.models.image_url.imageUrl(),
                quantity = 3
            )
        else:
            return ResolvedAddon(
                product_id = 'prod_addon_123',
                name = 'Extra Seats add-on',
                image_url = solifyn.models.image_url.imageUrl(),
                quantity = 3,
        )
        """

    def testResolvedAddon(self):
        """Test ResolvedAddon"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
