# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.licenses_update_instance_post_request import LicensesUpdateInstancePostRequest

class TestLicensesUpdateInstancePostRequest(unittest.TestCase):
    """LicensesUpdateInstancePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LicensesUpdateInstancePostRequest:
        """Test LicensesUpdateInstancePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LicensesUpdateInstancePostRequest`
        """
        model = LicensesUpdateInstancePostRequest()
        if include_optional:
            return LicensesUpdateInstancePostRequest(
                instance_name = 'MacBook Pro 16"',
                ip_address = '203.0.113.42'
            )
        else:
            return LicensesUpdateInstancePostRequest(
        )
        """

    def testLicensesUpdateInstancePostRequest(self):
        """Test LicensesUpdateInstancePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
