# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.api.orders_api import OrdersApi


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrdersApi()

    def tearDown(self) -> None:
        pass

    def test_orders_get(self) -> None:
        """Test case for orders_get

        Retrieve Order
        """
        pass

    def test_orders_get_invoice(self) -> None:
        """Test case for orders_get_invoice

        Get Order Invoice
        """
        pass

    def test_orders_list(self) -> None:
        """Test case for orders_list

        List Orders
        """
        pass

    def test_orders_update(self) -> None:
        """Test case for orders_update

        Update Order Billing Address
        """
        pass

    def test_refunds_create(self) -> None:
        """Test case for refunds_create

        Create Refund
        """
        pass


if __name__ == '__main__':
    unittest.main()
