# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.collection_response_dto import CollectionResponseDto

class TestCollectionResponseDto(unittest.TestCase):
    """CollectionResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionResponseDto:
        """Test CollectionResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionResponseDto`
        """
        model = CollectionResponseDto()
        if include_optional:
            return CollectionResponseDto(
                id = '',
                name = 'Summer Bundle',
                description = 'Everything you need for summer.',
                image_url = 'https://example.com/image.png',
                status = 'ACTIVE',
                business_id = 'biz_4r5t6y7u8i9o',
                is_permanently_deleted = False,
                created_at = '2025-01-01T12:00Z',
                updated_at = '2025-01-01T12:00Z',
                products = [
                    solifyn.models.collection_product_ref_dto.CollectionProductRefDto(
                        id = 'prod_NG0mkkz0Awitk', 
                        quantity = 1, )
                    ]
            )
        else:
            return CollectionResponseDto(
                id = '',
                name = 'Summer Bundle',
                status = 'ACTIVE',
                business_id = 'biz_4r5t6y7u8i9o',
                is_permanently_deleted = False,
                created_at = '2025-01-01T12:00Z',
                updated_at = '2025-01-01T12:00Z',
        )
        """

    def testCollectionResponseDto(self):
        """Test CollectionResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
