# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.checkout_response_dto import CheckoutResponseDto

class TestCheckoutResponseDto(unittest.TestCase):
    """CheckoutResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutResponseDto:
        """Test CheckoutResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutResponseDto`
        """
        model = CheckoutResponseDto()
        if include_optional:
            return CheckoutResponseDto(
                id = '019e56ba-9832-72ae-XXXXXXXXXXX',
                session_id = 'ch_XXXXXXXXXXXXXX',
                checkout_url = 'http://localhost:3000/checkout/test/prod_XXXXXXXXXXX?checkout_id=019e56ba-9832-72ae-XXXXXXXXXX'
            )
        else:
            return CheckoutResponseDto(
                id = '019e56ba-9832-72ae-XXXXXXXXXXX',
                session_id = 'ch_XXXXXXXXXXXXXX',
                checkout_url = 'http://localhost:3000/checkout/test/prod_XXXXXXXXXXX?checkout_id=019e56ba-9832-72ae-XXXXXXXXXX',
        )
        """

    def testCheckoutResponseDto(self):
        """Test CheckoutResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
