# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.api.developer_api import DeveloperApi


class TestDeveloperApi(unittest.TestCase):
    """DeveloperApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeveloperApi()

    def tearDown(self) -> None:
        pass

    def test_developer_create_api_key(self) -> None:
        """Test case for developer_create_api_key

        Create Developer API Key
        """
        pass

    def test_developer_create_webhook(self) -> None:
        """Test case for developer_create_webhook

        Create Webhook Endpoint
        """
        pass

    def test_developer_delete_webhook(self) -> None:
        """Test case for developer_delete_webhook

        Delete Webhook Endpoint
        """
        pass

    def test_developer_get_app_portal(self) -> None:
        """Test case for developer_get_app_portal

        Retrieve Hosted Webhooks Portal URL
        """
        pass

    def test_developer_get_webhook(self) -> None:
        """Test case for developer_get_webhook

        Retrieve Webhook Endpoint Details
        """
        pass

    def test_developer_list_api_keys(self) -> None:
        """Test case for developer_list_api_keys

        List Developer API Keys
        """
        pass

    def test_developer_list_webhook_deliveries(self) -> None:
        """Test case for developer_list_webhook_deliveries

        Retrieve Webhook Delivery Logs
        """
        pass

    def test_developer_list_webhooks(self) -> None:
        """Test case for developer_list_webhooks

        List Webhook Endpoints
        """
        pass

    def test_developer_revoke_api_key(self) -> None:
        """Test case for developer_revoke_api_key

        Revoke API Key
        """
        pass

    def test_developer_update_webhook(self) -> None:
        """Test case for developer_update_webhook

        Update Webhook Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
