# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.api.customers_api import CustomersApi


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomersApi()

    def tearDown(self) -> None:
        pass

    def test_customers_create(self) -> None:
        """Test case for customers_create

        Create Customer
        """
        pass

    def test_customers_generate_invite(self) -> None:
        """Test case for customers_generate_invite

        Generate Shared Invite
        """
        pass

    def test_customers_get(self) -> None:
        """Test case for customers_get

        Retrieve Customer
        """
        pass

    def test_customers_list(self) -> None:
        """Test case for customers_list

        List Customers
        """
        pass

    def test_customers_update(self) -> None:
        """Test case for customers_update

        Update Customer
        """
        pass


if __name__ == '__main__':
    unittest.main()
