# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.api.disputes_api import DisputesApi


class TestDisputesApi(unittest.TestCase):
    """DisputesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DisputesApi()

    def tearDown(self) -> None:
        pass

    def test_disputes_generate_report(self) -> None:
        """Test case for disputes_generate_report

        Generate Dispute CSV Report
        """
        pass

    def test_disputes_get(self) -> None:
        """Test case for disputes_get

        Retrieve Dispute
        """
        pass

    def test_disputes_list(self) -> None:
        """Test case for disputes_list

        List Disputes
        """
        pass

    def test_disputes_submit_evidence(self) -> None:
        """Test case for disputes_submit_evidence

        Submit Dispute Evidence
        """
        pass

    def test_disputes_update_evidence(self) -> None:
        """Test case for disputes_update_evidence

        Update Dispute Evidence
        """
        pass

    def test_disputes_upload_evidence_file(self) -> None:
        """Test case for disputes_upload_evidence_file

        Upload Evidence File
        """
        pass


if __name__ == '__main__':
    unittest.main()
