# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.user_page import UserPage

class TestUserPage(unittest.TestCase):
    """UserPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserPage:
        """Test UserPage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserPage`
        """
        model = UserPage()
        if include_optional:
            return UserPage(
                id = 'page_123',
                subdomain = 'acme',
                store_name = 'Acme Shop',
                config = {"theme":{"primaryColor":"#0f172a"}},
                business_id = 'biz_123'
            )
        else:
            return UserPage(
                id = 'page_123',
                subdomain = 'acme',
                store_name = 'Acme Shop',
                config = {"theme":{"primaryColor":"#0f172a"}},
                business_id = 'biz_123',
        )
        """

    def testUserPage(self):
        """Test UserPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
