# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.api.git_hub_integration_api import GitHubIntegrationApi


class TestGitHubIntegrationApi(unittest.TestCase):
    """GitHubIntegrationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GitHubIntegrationApi()

    def tearDown(self) -> None:
        pass

    def test_github_get_install_url(self) -> None:
        """Test case for github_get_install_url

        Get GitHub App Installation URL
        """
        pass

    def test_github_list_repos(self) -> None:
        """Test case for github_list_repos

        List Available GitHub Repositories
        """
        pass


if __name__ == '__main__':
    unittest.main()
