# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.discord_roles_response_dto import DiscordRolesResponseDto

class TestDiscordRolesResponseDto(unittest.TestCase):
    """DiscordRolesResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiscordRolesResponseDto:
        """Test DiscordRolesResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiscordRolesResponseDto`
        """
        model = DiscordRolesResponseDto()
        if include_optional:
            return DiscordRolesResponseDto(
                id = '876543210987654321',
                name = 'VIP Member',
                position = 3,
                color = 3447003
            )
        else:
            return DiscordRolesResponseDto(
                id = '876543210987654321',
                name = 'VIP Member',
                position = 3,
                color = 3447003,
        )
        """

    def testDiscordRolesResponseDto(self):
        """Test DiscordRolesResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
