# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.api.brands_api import BrandsApi


class TestBrandsApi(unittest.TestCase):
    """BrandsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BrandsApi()

    def tearDown(self) -> None:
        pass

    def test_brands_create(self) -> None:
        """Test case for brands_create

        Create Brand
        """
        pass

    def test_brands_get(self) -> None:
        """Test case for brands_get

        Retrieve Brand
        """
        pass

    def test_brands_list(self) -> None:
        """Test case for brands_list

        List Brands
        """
        pass

    def test_brands_update(self) -> None:
        """Test case for brands_update

        Update Brand
        """
        pass


if __name__ == '__main__':
    unittest.main()
