# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.discount_create import DiscountCreate

class TestDiscountCreate(unittest.TestCase):
    """DiscountCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiscountCreate:
        """Test DiscountCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiscountCreate`
        """
        model = DiscountCreate()
        if include_optional:
            return DiscountCreate(
                code = '',
                name = '',
                type = 'percentage',
                amount = 1.337,
                usage_limit = 56,
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                subscription_cycles = 56,
                restricted_to = [
                    ''
                    ],
                preserve_on_plan_change = True,
                metadata = None
            )
        else:
            return DiscountCreate(
                code = '',
                type = 'percentage',
                amount = 1.337,
        )
        """

    def testDiscountCreate(self):
        """Test DiscountCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
