# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.api.webhook_endpoint_api import WebhookEndpointApi


class TestWebhookEndpointApi(unittest.TestCase):
    """WebhookEndpointApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhookEndpointApi()

    def tearDown(self) -> None:
        pass

    def test_operational_webhook_controller_create(self) -> None:
        """Test case for operational_webhook_controller_create

        Create Operational Webhook Endpoint
        """
        pass

    def test_operational_webhook_controller_delete(self) -> None:
        """Test case for operational_webhook_controller_delete

        Delete Operational Webhook Endpoint
        """
        pass

    def test_operational_webhook_controller_get(self) -> None:
        """Test case for operational_webhook_controller_get

        Get Operational Webhook Endpoint
        """
        pass

    def test_operational_webhook_controller_get_headers(self) -> None:
        """Test case for operational_webhook_controller_get_headers

        Get Operational Webhook Endpoint Headers
        """
        pass

    def test_operational_webhook_controller_get_secret(self) -> None:
        """Test case for operational_webhook_controller_get_secret

        Get Operational Webhook Endpoint Secret
        """
        pass

    def test_operational_webhook_controller_list(self) -> None:
        """Test case for operational_webhook_controller_list

        List Operational Webhook Endpoints
        """
        pass

    def test_operational_webhook_controller_rotate_secret(self) -> None:
        """Test case for operational_webhook_controller_rotate_secret

        Rotate Operational Webhook Endpoint Secret
        """
        pass

    def test_operational_webhook_controller_update(self) -> None:
        """Test case for operational_webhook_controller_update

        Update Operational Webhook Endpoint
        """
        pass

    def test_operational_webhook_controller_update_headers(self) -> None:
        """Test case for operational_webhook_controller_update_headers

        Set Operational Webhook Endpoint Headers
        """
        pass


if __name__ == '__main__':
    unittest.main()
