# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.api.user_profile_themes_api import UserProfileThemesApi


class TestUserProfileThemesApi(unittest.TestCase):
    """UserProfileThemesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserProfileThemesApi()

    def tearDown(self) -> None:
        pass

    def test_users_get_my_page(self) -> None:
        """Test case for users_get_my_page

        Get My Page details
        """
        pass

    def test_users_get_my_theme(self) -> None:
        """Test case for users_get_my_theme

        Get My Theme
        """
        pass

    def test_users_get_settings(self) -> None:
        """Test case for users_get_settings

        Retrieve User Settings
        """
        pass

    def test_users_get_stats(self) -> None:
        """Test case for users_get_stats

        Get Dashboard Statistics
        """
        pass

    def test_users_get_theme_by_subdomain(self) -> None:
        """Test case for users_get_theme_by_subdomain

        Get Theme by Subdomain
        """
        pass


if __name__ == '__main__':
    unittest.main()
