# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.discounts_list200_response import DiscountsList200Response

class TestDiscountsList200Response(unittest.TestCase):
    """DiscountsList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiscountsList200Response:
        """Test DiscountsList200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiscountsList200Response`
        """
        model = DiscountsList200Response()
        if include_optional:
            return DiscountsList200Response(
                items = [
                    solifyn.models.discount.Discount(
                        id = 'disc_cs8f67sd7f6fw3fs', 
                        discount_id = 'disc_cs8f67sd7f6fw3fs', 
                        code = '', 
                        name = '', 
                        type = 'percentage', 
                        amount = 56, 
                        usage_limit = 56, 
                        times_used = 56, 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'active', 
                        business_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 56,
                total_count = 56,
                pagination = solifyn.models.discounts_list_200_response_pagination.discounts_list_200_response_pagination(
                    total = 56, 
                    total_count = 56, 
                    max_page = 56, )
            )
        else:
            return DiscountsList200Response(
                items = [
                    solifyn.models.discount.Discount(
                        id = 'disc_cs8f67sd7f6fw3fs', 
                        discount_id = 'disc_cs8f67sd7f6fw3fs', 
                        code = '', 
                        name = '', 
                        type = 'percentage', 
                        amount = 56, 
                        usage_limit = 56, 
                        times_used = 56, 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'active', 
                        business_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 56,
                total_count = 56,
                pagination = solifyn.models.discounts_list_200_response_pagination.discounts_list_200_response_pagination(
                    total = 56, 
                    total_count = 56, 
                    max_page = 56, ),
        )
        """

    def testDiscountsList200Response(self):
        """Test DiscountsList200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
