# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.instance import Instance

class TestInstance(unittest.TestCase):
    """Instance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Instance:
        """Test Instance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Instance`
        """
        model = Instance()
        if include_optional:
            return Instance(
                id = '7f3a1b2c-4d5e-6f7a-8b9c-0d1e2f3a4b5c',
                license_id = 'lic_hyQQhhNzfEuvv',
                instance_id = 'machine-ID-abc123',
                instance_name = 'MacBook Pro 16"',
                ip_address = '203.0.113.42',
                activated_at = '2026-05-15T10:30:00.000Z',
                last_seen_at = '2026-05-18T08:00:00.000Z'
            )
        else:
            return Instance(
                id = '7f3a1b2c-4d5e-6f7a-8b9c-0d1e2f3a4b5c',
                license_id = 'lic_hyQQhhNzfEuvv',
                instance_id = 'machine-ID-abc123',
                instance_name = 'MacBook Pro 16"',
                ip_address = '203.0.113.42',
                activated_at = '2026-05-15T10:30:00.000Z',
                last_seen_at = '2026-05-18T08:00:00.000Z',
        )
        """

    def testInstance(self):
        """Test Instance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
