# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.api.license_keys_client_api import LicenseKeysClientApi


class TestLicenseKeysClientApi(unittest.TestCase):
    """LicenseKeysClientApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LicenseKeysClientApi()

    def tearDown(self) -> None:
        pass

    def test_licenses_activate(self) -> None:
        """Test case for licenses_activate

        Activate License Key
        """
        pass

    def test_licenses_deactivate(self) -> None:
        """Test case for licenses_deactivate

        Deactivate Instance
        """
        pass

    def test_licenses_instances(self) -> None:
        """Test case for licenses_instances

        Get Active Instances
        """
        pass

    def test_licenses_verify(self) -> None:
        """Test case for licenses_verify

        Validate License Key
        """
        pass


if __name__ == '__main__':
    unittest.main()
