# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.meter_quantities_response_dto import MeterQuantitiesResponseDto

class TestMeterQuantitiesResponseDto(unittest.TestCase):
    """MeterQuantitiesResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeterQuantitiesResponseDto:
        """Test MeterQuantitiesResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeterQuantitiesResponseDto`
        """
        model = MeterQuantitiesResponseDto()
        if include_optional:
            return MeterQuantitiesResponseDto(
                meter_id = 'mtr_8Z1aB2cD3eF4gH5iJ6kL7m',
                name = 'API Request Count',
                total_usage = 1540,
                costs = [
                    solifyn.models.meter_quantities_cost_dto.MeterQuantitiesCostDto(
                        product_id = 'prod_9z8x7c6v5b4n', 
                        total_usage = 1540, 
                        billable_usage = 1500, 
                        cost = 19.5, 
                        currency = 'USD', )
                    ]
            )
        else:
            return MeterQuantitiesResponseDto(
                meter_id = 'mtr_8Z1aB2cD3eF4gH5iJ6kL7m',
                name = 'API Request Count',
                total_usage = 1540,
                costs = [
                    solifyn.models.meter_quantities_cost_dto.MeterQuantitiesCostDto(
                        product_id = 'prod_9z8x7c6v5b4n', 
                        total_usage = 1540, 
                        billable_usage = 1500, 
                        cost = 19.5, 
                        currency = 'USD', )
                    ],
        )
        """

    def testMeterQuantitiesResponseDto(self):
        """Test MeterQuantitiesResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
