# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.customer_response_dto import CustomerResponseDto

class TestCustomerResponseDto(unittest.TestCase):
    """CustomerResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerResponseDto:
        """Test CustomerResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerResponseDto`
        """
        model = CustomerResponseDto()
        if include_optional:
            return CustomerResponseDto(
                id = 'user_123',
                member_id = 'mem_123',
                email = 'customer@example.com',
                name = 'John Doe',
                username = 'johndoe',
                phone = '+1234567890',
                phone_number = '+1234567890',
                metadata = {"key":"value"},
                created_at = '2025-01-01T12:00Z',
                updated_at = '2025-01-01T12:00Z',
                business_id = '537825c3-14d6-4173-b072-33f921416efc'
            )
        else:
            return CustomerResponseDto(
                id = 'user_123',
                email = 'customer@example.com',
                created_at = '2025-01-01T12:00Z',
                updated_at = '2025-01-01T12:00Z',
                business_id = '537825c3-14d6-4173-b072-33f921416efc',
        )
        """

    def testCustomerResponseDto(self):
        """Test CustomerResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
