# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.user_stats import UserStats

class TestUserStats(unittest.TestCase):
    """UserStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserStats:
        """Test UserStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserStats`
        """
        model = UserStats()
        if include_optional:
            return UserStats(
                summary = solifyn.models.dashboard_stats_dto.DashboardStatsDto(
                    revenue = 500000, 
                    orders_count = 120, 
                    refunds_count = 1500, 
                    active_memberships = 85, ),
                chart_data = [{"date":"2025-01-01","revenue":12000,"orders":3}]
            )
        else:
            return UserStats(
                summary = solifyn.models.dashboard_stats_dto.DashboardStatsDto(
                    revenue = 500000, 
                    orders_count = 120, 
                    refunds_count = 1500, 
                    active_memberships = 85, ),
                chart_data = [{"date":"2025-01-01","revenue":12000,"orders":3}],
        )
        """

    def testUserStats(self):
        """Test UserStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
