# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.brand_create import BrandCreate

class TestBrandCreate(unittest.TestCase):
    """BrandCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandCreate:
        """Test BrandCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandCreate`
        """
        model = BrandCreate()
        if include_optional:
            return BrandCreate(
                name = 'Acme Corp',
                website_url = 'https://acme.com',
                support_email = 'support@acme.com',
                description = 'A leading provider of ACME tools.',
                logo_url = 'https://acme.com/logo.png',
                statement_descriptor = 'ACME CORP INC'
            )
        else:
            return BrandCreate(
                name = 'Acme Corp',
        )
        """

    def testBrandCreate(self):
        """Test BrandCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
