# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.licenses_create_request import LicensesCreateRequest

class TestLicensesCreateRequest(unittest.TestCase):
    """LicensesCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LicensesCreateRequest:
        """Test LicensesCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LicensesCreateRequest`
        """
        model = LicensesCreateRequest()
        if include_optional:
            return LicensesCreateRequest(
                product_id = '',
                customer_id = '',
                activation_limit = 56,
                expiry_hours = 56,
                key = ''
            )
        else:
            return LicensesCreateRequest(
                product_id = '',
                customer_id = '',
        )
        """

    def testLicensesCreateRequest(self):
        """Test LicensesCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
