# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.api.entitlements_api import EntitlementsApi


class TestEntitlementsApi(unittest.TestCase):
    """EntitlementsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EntitlementsApi()

    def tearDown(self) -> None:
        pass

    def test_entitlements_create(self) -> None:
        """Test case for entitlements_create

        Create Entitlement
        """
        pass

    def test_entitlements_delete(self) -> None:
        """Test case for entitlements_delete

        Delete Entitlement
        """
        pass

    def test_entitlements_get(self) -> None:
        """Test case for entitlements_get

        Retrieve Entitlement
        """
        pass

    def test_entitlements_list(self) -> None:
        """Test case for entitlements_list

        List Entitlements
        """
        pass

    def test_entitlements_update(self) -> None:
        """Test case for entitlements_update

        Update Entitlement
        """
        pass


if __name__ == '__main__':
    unittest.main()
