# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.api.partner_api import PartnerApi


class TestPartnerApi(unittest.TestCase):
    """PartnerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PartnerApi()

    def tearDown(self) -> None:
        pass

    def test_partner_controller_get_partner_commissions(self) -> None:
        """Test case for partner_controller_get_partner_commissions

        """
        pass

    def test_partner_controller_get_partner_stats(self) -> None:
        """Test case for partner_controller_get_partner_stats

        """
        pass


if __name__ == '__main__':
    unittest.main()
