# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.meter_detail_response_dto import MeterDetailResponseDto

class TestMeterDetailResponseDto(unittest.TestCase):
    """MeterDetailResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeterDetailResponseDto:
        """Test MeterDetailResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeterDetailResponseDto`
        """
        model = MeterDetailResponseDto()
        if include_optional:
            return MeterDetailResponseDto(
                id = 'mtr_8Z1aB2cD3eF4gH5iJ6kL7m',
                business_id = 'biz_4r5t6y7u8i9o',
                name = 'API Request Count',
                description = Counts successful API requests for usage-based billing.,
                event_name = 'api.request',
                aggregation_type = 'COUNT',
                aggregation_key = tokens,
                unit = requests,
                filters = {"event_type":"premium","region":"asia"},
                archived = False,
                created_at = '2026-05-23T10:00Z',
                updated_at = '2026-05-23T10:00Z',
                usage_events = [
                    solifyn.models.meter_usage_event_dto.MeterUsageEventDto(
                        id = 'evt_9Y3kP4qR7tU1vW2xZ5aB6c', 
                        meter_id = 'mtr_8Z1aB2cD3eF4gH5iJ6kL7m', 
                        customer_id = 'cus_8n7m6l5k4j3h2g1f0e9d8c', 
                        value = 1, 
                        metadata = {"plan":"enterprise","region":"asia-southeast-1"}, 
                        timestamp = '2026-05-23T10:00Z', 
                        processed_at = '2026-05-23T10:00:01Z', )
                    ],
                total_usage_events = 1284
            )
        else:
            return MeterDetailResponseDto(
                id = 'mtr_8Z1aB2cD3eF4gH5iJ6kL7m',
                business_id = 'biz_4r5t6y7u8i9o',
                name = 'API Request Count',
                event_name = 'api.request',
                aggregation_type = 'COUNT',
                archived = False,
                created_at = '2026-05-23T10:00Z',
                updated_at = '2026-05-23T10:00Z',
                usage_events = [
                    solifyn.models.meter_usage_event_dto.MeterUsageEventDto(
                        id = 'evt_9Y3kP4qR7tU1vW2xZ5aB6c', 
                        meter_id = 'mtr_8Z1aB2cD3eF4gH5iJ6kL7m', 
                        customer_id = 'cus_8n7m6l5k4j3h2g1f0e9d8c', 
                        value = 1, 
                        metadata = {"plan":"enterprise","region":"asia-southeast-1"}, 
                        timestamp = '2026-05-23T10:00Z', 
                        processed_at = '2026-05-23T10:00:01Z', )
                    ],
                total_usage_events = 1284,
        )
        """

    def testMeterDetailResponseDto(self):
        """Test MeterDetailResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
