# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.user_settings import UserSettings

class TestUserSettings(unittest.TestCase):
    """UserSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSettings:
        """Test UserSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSettings`
        """
        model = UserSettings()
        if include_optional:
            return UserSettings(
                id = 'usr_123',
                email = 'contact@acme.com',
                first_name = 'John',
                last_name = 'Doe',
                avatar_url = 'https://acme.com/avatar.png',
                payout_threshold = 5000,
                notify_on_success = True,
                send_license_key_email = True,
                send_digital_file_email = True
            )
        else:
            return UserSettings(
                id = 'usr_123',
                email = 'contact@acme.com',
                payout_threshold = 5000,
                notify_on_success = True,
                send_license_key_email = True,
                send_digital_file_email = True,
        )
        """

    def testUserSettings(self):
        """Test UserSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
