# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.create_webhook_endpoint_dto import CreateWebhookEndpointDto

class TestCreateWebhookEndpointDto(unittest.TestCase):
    """CreateWebhookEndpointDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWebhookEndpointDto:
        """Test CreateWebhookEndpointDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWebhookEndpointDto`
        """
        model = CreateWebhookEndpointDto()
        if include_optional:
            return CreateWebhookEndpointDto(
                url = 'https://api.example.com/webhooks',
                description = 'Primary payment listener',
                events = [payment.created, payment.succeeded]
            )
        else:
            return CreateWebhookEndpointDto(
                url = 'https://api.example.com/webhooks',
                events = [payment.created, payment.succeeded],
        )
        """

    def testCreateWebhookEndpointDto(self):
        """Test CreateWebhookEndpointDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
