# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.withdrawal import Withdrawal

class TestWithdrawal(unittest.TestCase):
    """Withdrawal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Withdrawal:
        """Test Withdrawal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Withdrawal`
        """
        model = Withdrawal()
        if include_optional:
            return Withdrawal(
                id = 'wd_123',
                whop_id = 'wdrl_123',
                amount = 1000,
                currency = 'usd',
                status = 'completed',
                fee_amount = 150,
                fee_type = 'exclusive',
                markup_fee = 50,
                speed = 'standard',
                trace_code = 'TR123456789',
                payer_name = 'Whop Payments',
                error_message = 'Insufficient funds in balance',
                business_id = 'biz_123',
                created_at = '2025-01-01T12:00:00Z',
                updated_at = '2025-01-01T12:00:00Z'
            )
        else:
            return Withdrawal(
                id = 'wd_123',
                whop_id = 'wdrl_123',
                amount = 1000,
                currency = 'usd',
                status = 'completed',
                business_id = 'biz_123',
                created_at = '2025-01-01T12:00:00Z',
                updated_at = '2025-01-01T12:00:00Z',
        )
        """

    def testWithdrawal(self):
        """Test Withdrawal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
