# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.customer_shared_invite_response_dto import CustomerSharedInviteResponseDto

class TestCustomerSharedInviteResponseDto(unittest.TestCase):
    """CustomerSharedInviteResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerSharedInviteResponseDto:
        """Test CustomerSharedInviteResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerSharedInviteResponseDto`
        """
        model = CustomerSharedInviteResponseDto()
        if include_optional:
            return CustomerSharedInviteResponseDto(
                token = '2jb5bp8bq0jfucv7rtt9a8',
                expires_at = '2025-01-02T12:00Z',
                url = 'http://localhost:3000/shared/2jb5bp8bq0jfucv7rtt9a8'
            )
        else:
            return CustomerSharedInviteResponseDto(
                token = '2jb5bp8bq0jfucv7rtt9a8',
                expires_at = '2025-01-02T12:00Z',
        )
        """

    def testCustomerSharedInviteResponseDto(self):
        """Test CustomerSharedInviteResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
