# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.webhook_payment_payload_billing_address import WebhookPaymentPayloadBillingAddress

class TestWebhookPaymentPayloadBillingAddress(unittest.TestCase):
    """WebhookPaymentPayloadBillingAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookPaymentPayloadBillingAddress:
        """Test WebhookPaymentPayloadBillingAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookPaymentPayloadBillingAddress`
        """
        model = WebhookPaymentPayloadBillingAddress()
        if include_optional:
            return WebhookPaymentPayloadBillingAddress(
                name = '',
                line1 = '',
                line2 = '',
                city = '',
                state = '',
                country = '',
                postal_code = ''
            )
        else:
            return WebhookPaymentPayloadBillingAddress(
        )
        """

    def testWebhookPaymentPayloadBillingAddress(self):
        """Test WebhookPaymentPayloadBillingAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
