# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.linked_product_dto import LinkedProductDto

class TestLinkedProductDto(unittest.TestCase):
    """LinkedProductDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkedProductDto:
        """Test LinkedProductDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkedProductDto`
        """
        model = LinkedProductDto()
        if include_optional:
            return LinkedProductDto(
                id = 'prod_12345',
                name = 'Premium Developer Plan'
            )
        else:
            return LinkedProductDto(
                id = 'prod_12345',
                name = 'Premium Developer Plan',
        )
        """

    def testLinkedProductDto(self):
        """Test LinkedProductDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
