# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.subscriptions_action201_response import SubscriptionsAction201Response

class TestSubscriptionsAction201Response(unittest.TestCase):
    """SubscriptionsAction201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionsAction201Response:
        """Test SubscriptionsAction201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionsAction201Response`
        """
        model = SubscriptionsAction201Response()
        if include_optional:
            return SubscriptionsAction201Response(
                id = 'mem_123',
                status = 'active',
                created_at = '2025-01-01T12:00Z',
                joined_at = '2025-01-01T12:00Z',
                updated_at = '2025-01-01T12:00Z',
                manage_url = 'https://example.com/billing/manage/mber_123',
                member = solifyn.models.subscription_member_dto.SubscriptionMemberDto(
                    id = 'mber_123', ),
                user = solifyn.models.subscription_user_dto.SubscriptionUserDto(
                    id = 'user_123', 
                    username = 'johndoe', 
                    name = 'John Doe', 
                    email = 'john.doe@example.com', ),
                renewal_period_start = solifyn.models.renewal_period_start.renewal_period_start(),
                renewal_period_end = solifyn.models.renewal_period_end.renewal_period_end(),
                cancel_at_period_end = False,
                cancel_option = solifyn.models.cancel_option.cancel_option(),
                cancellation_reason = solifyn.models.cancellation_reason.cancellation_reason(),
                canceled_at = solifyn.models.canceled_at.canceled_at(),
                currency = 'usd',
                company = solifyn.models.subscription_company_dto.SubscriptionCompanyDto(
                    id = 'biz_123', 
                    title = 'Company Name', ),
                plan = solifyn.models.subscription_plan_dto.SubscriptionPlanDto(
                    id = 'plan_123', 
                    metadata = {}, ),
                promo_code = solifyn.models.promo_code.promo_code(),
                product = solifyn.models.subscription_product_dto.SubscriptionProductDto(
                    id = 'prod_123', 
                    title = 'Product Name', 
                    metadata = {}, ),
                license_key = solifyn.models.license_key.license_key(),
                metadata = {is_usage_based=false},
                payment_collection_paused = False,
                checkout_configuration_id = 'ch_123',
                price = 99,
                type = renewal,
                customer_id = cust_123,
                success = True,
                subscription_id = 'mem_123',
                addon_product_id = 'prod_seat_123',
                old_quantity = 2,
                new_quantity = 5,
                quantity_delta = 3,
                proration_type = 'do_not_bill',
                cost_impact = 0
            )
        else:
            return SubscriptionsAction201Response(
                id = 'mem_123',
                status = 'active',
                created_at = '2025-01-01T12:00Z',
                joined_at = '2025-01-01T12:00Z',
                updated_at = '2025-01-01T12:00Z',
                manage_url = 'https://example.com/billing/manage/mber_123',
                member = solifyn.models.subscription_member_dto.SubscriptionMemberDto(
                    id = 'mber_123', ),
                user = solifyn.models.subscription_user_dto.SubscriptionUserDto(
                    id = 'user_123', 
                    username = 'johndoe', 
                    name = 'John Doe', 
                    email = 'john.doe@example.com', ),
                renewal_period_start = solifyn.models.renewal_period_start.renewal_period_start(),
                renewal_period_end = solifyn.models.renewal_period_end.renewal_period_end(),
                cancel_at_period_end = False,
                cancel_option = solifyn.models.cancel_option.cancel_option(),
                cancellation_reason = solifyn.models.cancellation_reason.cancellation_reason(),
                canceled_at = solifyn.models.canceled_at.canceled_at(),
                currency = 'usd',
                company = solifyn.models.subscription_company_dto.SubscriptionCompanyDto(
                    id = 'biz_123', 
                    title = 'Company Name', ),
                plan = solifyn.models.subscription_plan_dto.SubscriptionPlanDto(
                    id = 'plan_123', 
                    metadata = {}, ),
                promo_code = solifyn.models.promo_code.promo_code(),
                product = solifyn.models.subscription_product_dto.SubscriptionProductDto(
                    id = 'prod_123', 
                    title = 'Product Name', 
                    metadata = {}, ),
                license_key = solifyn.models.license_key.license_key(),
                metadata = {is_usage_based=false},
                payment_collection_paused = False,
                checkout_configuration_id = 'ch_123',
                success = True,
                subscription_id = 'mem_123',
                addon_product_id = 'prod_seat_123',
                old_quantity = 2,
                new_quantity = 5,
                quantity_delta = 3,
                proration_type = 'do_not_bill',
                cost_impact = 0,
        )
        """

    def testSubscriptionsAction201Response(self):
        """Test SubscriptionsAction201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
