# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.api.refund_requests_api import RefundRequestsApi


class TestRefundRequestsApi(unittest.TestCase):
    """RefundRequestsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RefundRequestsApi()

    def tearDown(self) -> None:
        pass

    def test_refund_requests_list(self) -> None:
        """Test case for refund_requests_list

        List Refund Requests (Merchant)
        """
        pass

    def test_refund_requests_list_messages(self) -> None:
        """Test case for refund_requests_list_messages

        List Messages for Refund Request (Merchant)
        """
        pass

    def test_refund_requests_send_message(self) -> None:
        """Test case for refund_requests_send_message

        Send Refund Request Message (Merchant)
        """
        pass

    def test_refund_requests_update_status(self) -> None:
        """Test case for refund_requests_update_status

        Update Refund Request Status (Merchant)
        """
        pass

    def test_refund_requests_upload_evidence(self) -> None:
        """Test case for refund_requests_upload_evidence

        Upload Dispute Evidence File (Merchant)
        """
        pass


if __name__ == '__main__':
    unittest.main()
