# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.create_entitlement_dto import CreateEntitlementDto

class TestCreateEntitlementDto(unittest.TestCase):
    """CreateEntitlementDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEntitlementDto:
        """Test CreateEntitlementDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEntitlementDto`
        """
        model = CreateEntitlementDto()
        if include_optional:
            return CreateEntitlementDto(
                name = 'Premium GitHub Access',
                type = 'GITHUB',
                github_repo = 'solifyn/premium-repo',
                github_permission = 'pull',
                discord_guild_id = '123456789012345678',
                discord_role_id = '876543210987654321',
                framer_template_id = 'framer_tmpl_123',
                license_key = 'whsec_license_key_123',
                activation_limit = 3,
                activation_message = 'Thank you for activating your software license!',
                expiry_hours = 720,
                digital_link = 'https://downloads.solifyn.com/file.zip',
                instructions = 'Clone the repository and run npm install.'
            )
        else:
            return CreateEntitlementDto(
                name = 'Premium GitHub Access',
                type = 'GITHUB',
        )
        """

    def testCreateEntitlementDto(self):
        """Test CreateEntitlementDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
