# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.user_settings_update import UserSettingsUpdate

class TestUserSettingsUpdate(unittest.TestCase):
    """UserSettingsUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSettingsUpdate:
        """Test UserSettingsUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSettingsUpdate`
        """
        model = UserSettingsUpdate()
        if include_optional:
            return UserSettingsUpdate(
                subdomain = 'acme',
                store_name = 'Acme Store',
                social_links = None,
                page_title = 'Acme - Shop',
                seo_description = 'Buy Acme products here',
                seo_image = 'https://acme.com/seo.png',
                favicon_url = 'https://acme.com/favicon.ico',
                google_analytics_id = 'G-XXXXXX',
                google_tag_manager_id = 'GTM-XXXXXX',
                meta_pixel_id = '1234567890',
                logo_url = 'https://acme.com/logo.png',
                business_title = 'Acme Inc',
                statement_descriptor = 'ACME SHOP',
                default_currency = 'USD',
                email = 'contact@acme.com',
                first_name = 'John',
                last_name = 'Doe',
                avatar_url = 'https://acme.com/profile.png',
                payout_threshold = 5000,
                notify_on_success = True,
                send_license_key_email = True,
                send_digital_file_email = True,
                notify_on_subscription_plan_changed = True,
                notify_on_subscription_set_to_cancel = True,
                notify_on_subscription_cancelled = True,
                notify_on_refund_successful = True,
                notify_on_payment_failed = True,
                notify_on_subscription_renewal_failed = True,
                notify_on_subscription_trial_ending = True,
                notify_on_subscription_paused = True
            )
        else:
            return UserSettingsUpdate(
        )
        """

    def testUserSettingsUpdate(self):
        """Test UserSettingsUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
