# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solifyn.models.operational_webhook_endpoint_in_dto import OperationalWebhookEndpointInDto

class TestOperationalWebhookEndpointInDto(unittest.TestCase):
    """OperationalWebhookEndpointInDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OperationalWebhookEndpointInDto:
        """Test OperationalWebhookEndpointInDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OperationalWebhookEndpointInDto`
        """
        model = OperationalWebhookEndpointInDto()
        if include_optional:
            return OperationalWebhookEndpointInDto(
                url = 'https://example.com/webhook/',
                description = 'Production monitoring endpoint',
                disabled = False,
                filter_types = ["message.attempt.failing","message.attempt.exhausted"],
                metadata = {"environment":"production"},
                secret = 'whsec_C2FVsBQIhrscChlQIMV+b5sSYspob7oD',
                throttle_rate = 5,
                uid = 'monitoring-prod-endpoint'
            )
        else:
            return OperationalWebhookEndpointInDto(
                url = 'https://example.com/webhook/',
        )
        """

    def testOperationalWebhookEndpointInDto(self):
        """Test OperationalWebhookEndpointInDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
