# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Business(BaseModel):
    """
    Business
    """ # noqa: E501
    id: StrictStr = Field(description="The unique business ID")
    title: StrictStr = Field(description="Title or name of the business")
    description: Optional[StrictStr] = Field(default=None, description="A description explaining what the business does")
    whop_id: StrictStr = Field(description="The Whop Company ID", alias="whopId")
    merchant_id: StrictStr = Field(description="The merchant owner ID", alias="merchantId")
    verified: StrictBool = Field(description="Whether the business has been KYC-verified on Whop")
    send_customer_emails: StrictBool = Field(description="Whether auto-emails are enabled for customers", alias="sendCustomerEmails")
    member_count: Union[StrictFloat, StrictInt] = Field(description="Total members/customers under this business", alias="memberCount")
    route: Optional[StrictStr] = Field(default=None, description="Whop friendly URL path route")
    default_currency: StrictStr = Field(description="The default currency of the business", alias="defaultCurrency")
    published_reviews_count: Union[StrictFloat, StrictInt] = Field(description="Number of published user reviews on Whop", alias="publishedReviewsCount")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Custom key-value metadata")
    target_audience: Optional[StrictStr] = Field(default=None, description="The target audience description", alias="targetAudience")
    social_links: Optional[Dict[str, Any]] = Field(default=None, description="Social links setup", alias="socialLinks")
    affiliate_instructions: Optional[StrictStr] = Field(default=None, description="Markdown instructions for affiliates", alias="affiliateInstructions")
    whop_created_at: Optional[datetime] = Field(default=None, description="Whop account creation timestamp", alias="whopCreatedAt")
    whop_updated_at: Optional[datetime] = Field(default=None, description="Whop account last updated timestamp", alias="whopUpdatedAt")
    created_at: datetime = Field(description="Timestamp when the business record was created", alias="createdAt")
    updated_at: datetime = Field(description="Timestamp when the business record was last updated", alias="updatedAt")
    logo_url: Optional[StrictStr] = Field(default=None, description="Brand logo image URL resolved from primary brand", alias="logoUrl")
    __properties: ClassVar[List[str]] = ["id", "title", "description", "whopId", "merchantId", "verified", "sendCustomerEmails", "memberCount", "route", "defaultCurrency", "publishedReviewsCount", "metadata", "targetAudience", "socialLinks", "affiliateInstructions", "whopCreatedAt", "whopUpdatedAt", "createdAt", "updatedAt", "logoUrl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Business from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Business from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "whopId": obj.get("whopId"),
            "merchantId": obj.get("merchantId"),
            "verified": obj.get("verified"),
            "sendCustomerEmails": obj.get("sendCustomerEmails"),
            "memberCount": obj.get("memberCount"),
            "route": obj.get("route"),
            "defaultCurrency": obj.get("defaultCurrency"),
            "publishedReviewsCount": obj.get("publishedReviewsCount"),
            "metadata": obj.get("metadata"),
            "targetAudience": obj.get("targetAudience"),
            "socialLinks": obj.get("socialLinks"),
            "affiliateInstructions": obj.get("affiliateInstructions"),
            "whopCreatedAt": obj.get("whopCreatedAt"),
            "whopUpdatedAt": obj.get("whopUpdatedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "logoUrl": obj.get("logoUrl")
        })
        return _obj


