# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CreateCollectionCheckoutDto(BaseModel):
    """
    CreateCollectionCheckoutDto
    """ # noqa: E501
    collection_id: StrictStr = Field(description="The database ID of the collection to checkout", alias="collectionId")
    quantity: Optional[Union[StrictFloat, StrictInt]] = Field(default=1, description="Quantity of collections to buy")
    discount_code: Optional[StrictStr] = Field(default=None, description="Discount code to apply", alias="discountCode")
    aff: Optional[StrictStr] = Field(default=None, description="Affiliate tracking code")
    custom_fields: Optional[Dict[str, Any]] = Field(default=None, description="Custom text fields / selected addons", alias="customFields")
    __properties: ClassVar[List[str]] = ["collectionId", "quantity", "discountCode", "aff", "customFields"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateCollectionCheckoutDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateCollectionCheckoutDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "collectionId": obj.get("collectionId"),
            "quantity": obj.get("quantity") if obj.get("quantity") is not None else 1,
            "discountCode": obj.get("discountCode"),
            "aff": obj.get("aff"),
            "customFields": obj.get("customFields")
        })
        return _obj


