# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CreateCheckoutLinkDto(BaseModel):
    """
    CreateCheckoutLinkDto
    """ # noqa: E501
    title: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="The friendly display title of this checkout link")
    product_id: Annotated[str, Field(strict=True, max_length=50)] = Field(description="Product database/Whop ID to sell", alias="productId")
    collection_id: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="Optional collection database ID to sell", alias="collectionId")
    customer_name: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="Prefilled customer name for checkout inputs", alias="customerName")
    customer_email: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Prefilled customer email for checkout inputs", alias="customerEmail")
    address_line1: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Prefilled customer billing address line 1", alias="addressLine1")
    city: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="Prefilled customer billing city")
    state: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="Prefilled customer billing state")
    postal_code: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, description="Prefilled customer billing zip/postal code", alias="postalCode")
    country: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="Prefilled customer billing country (2-letter ISO)")
    quantity: Optional[Dict[str, Any]] = Field(default=None, description="Override quantity for checkout session")
    redirect_url: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = Field(default=None, description="The absolute URL to redirect to upon successful payment completion", alias="redirectUrl")
    cancel_url: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = Field(default=None, description="The absolute URL to redirect to if a customer cancels the payment", alias="cancelUrl")
    show_discounts: Optional[StrictBool] = Field(default=True, description="Whether to display discount input form fields on checkout screen", alias="showDiscounts")
    __properties: ClassVar[List[str]] = ["title", "productId", "collectionId", "customerName", "customerEmail", "addressLine1", "city", "state", "postalCode", "country", "quantity", "redirectUrl", "cancelUrl", "showDiscounts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateCheckoutLinkDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateCheckoutLinkDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "productId": obj.get("productId"),
            "collectionId": obj.get("collectionId"),
            "customerName": obj.get("customerName"),
            "customerEmail": obj.get("customerEmail"),
            "addressLine1": obj.get("addressLine1"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "postalCode": obj.get("postalCode"),
            "country": obj.get("country"),
            "quantity": obj.get("quantity"),
            "redirectUrl": obj.get("redirectUrl"),
            "cancelUrl": obj.get("cancelUrl"),
            "showDiscounts": obj.get("showDiscounts") if obj.get("showDiscounts") is not None else True
        })
        return _obj


