# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from solifyn.models.linked_product_dto import LinkedProductDto
from typing import Optional, Set
from typing_extensions import Self

class EntitlementDetailResponseDto(BaseModel):
    """
    EntitlementDetailResponseDto
    """ # noqa: E501
    id: StrictStr = Field(description="The unique entitlement ID")
    business_id: StrictStr = Field(description="The owning business ID", alias="businessId")
    name: StrictStr = Field(description="The name of the entitlement")
    type: StrictStr = Field(description="The type of access to grant")
    status: StrictStr = Field(description="Status of the entitlement")
    created_at: datetime = Field(description="When the entitlement was created", alias="createdAt")
    updated_at: datetime = Field(description="When the entitlement was last updated", alias="updatedAt")
    github_repo: Optional[StrictStr] = Field(default=None, description="The GitHub repository (e.g., owner/repo)", alias="githubRepo")
    github_permission: Optional[StrictStr] = Field(default=None, description="The GitHub repository permission level", alias="githubPermission")
    discord_guild_id: Optional[StrictStr] = Field(default=None, description="The Discord Guild/Server ID", alias="discordGuildId")
    discord_role_id: Optional[StrictStr] = Field(default=None, description="The Discord Role ID to assign", alias="discordRoleId")
    framer_template_id: Optional[StrictStr] = Field(default=None, description="The associated Framer Template ID", alias="framerTemplateId")
    license_key: Optional[StrictStr] = Field(default=None, description="The static License Key (if not dynamically generated)", alias="licenseKey")
    activation_limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The maximum activation limit for licenses", alias="activationLimit")
    activation_message: Optional[StrictStr] = Field(default=None, description="A message shown to the user upon license activation", alias="activationMessage")
    expiry_hours: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of hours until the entitlement expires", alias="expiryHours")
    digital_link: Optional[StrictStr] = Field(default=None, description="The digital download URL or redirect link", alias="digitalLink")
    instructions: Optional[StrictStr] = Field(default=None, description="Custom setup instructions for the user")
    grants_count: Union[StrictFloat, StrictInt] = Field(description="Number of active customer grants issued from this entitlement", alias="grantsCount")
    products: List[LinkedProductDto] = Field(description="Products that are currently linked to this entitlement")
    __properties: ClassVar[List[str]] = ["id", "businessId", "name", "type", "status", "createdAt", "updatedAt", "githubRepo", "githubPermission", "discordGuildId", "discordRoleId", "framerTemplateId", "licenseKey", "activationLimit", "activationMessage", "expiryHours", "digitalLink", "instructions", "grantsCount", "products"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntitlementDetailResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in products (list)
        _items = []
        if self.products:
            for _item_products in self.products:
                if _item_products:
                    _items.append(_item_products.to_dict())
            _dict['products'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntitlementDetailResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "businessId": obj.get("businessId"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "status": obj.get("status"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "githubRepo": obj.get("githubRepo"),
            "githubPermission": obj.get("githubPermission"),
            "discordGuildId": obj.get("discordGuildId"),
            "discordRoleId": obj.get("discordRoleId"),
            "framerTemplateId": obj.get("framerTemplateId"),
            "licenseKey": obj.get("licenseKey"),
            "activationLimit": obj.get("activationLimit"),
            "activationMessage": obj.get("activationMessage"),
            "expiryHours": obj.get("expiryHours"),
            "digitalLink": obj.get("digitalLink"),
            "instructions": obj.get("instructions"),
            "grantsCount": obj.get("grantsCount"),
            "products": [LinkedProductDto.from_dict(_item) for _item in obj["products"]] if obj.get("products") is not None else None
        })
        return _obj


