# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class Instance(BaseModel):
    """
    Represents an active device or software instance that has been activated against a license key.
    """ # noqa: E501
    id: StrictStr = Field(description="The unique database identifier of this instance record.")
    license_id: StrictStr = Field(description="The internal ID of the parent license key this instance belongs to.", alias="licenseId")
    instance_id: StrictStr = Field(description="The unique hardware hash or client-generated identifier of the activated device/machine.", alias="instanceId")
    instance_name: StrictStr = Field(description="A human-readable display name for this instance, assigned by the client application.", alias="instanceName")
    ip_address: StrictStr = Field(description="The IP address recorded at the time of activation.", alias="ipAddress")
    activated_at: StrictStr = Field(description="Timestamp when this device instance was first activated.", alias="activatedAt")
    last_seen_at: StrictStr = Field(description="Timestamp of the most recent activation heartbeat or re-activation check from this device.", alias="lastSeenAt")
    __properties: ClassVar[List[str]] = ["id", "licenseId", "instanceId", "instanceName", "ipAddress", "activatedAt", "lastSeenAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Instance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Instance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "licenseId": obj.get("licenseId"),
            "instanceId": obj.get("instanceId"),
            "instanceName": obj.get("instanceName"),
            "ipAddress": obj.get("ipAddress"),
            "activatedAt": obj.get("activatedAt"),
            "lastSeenAt": obj.get("lastSeenAt")
        })
        return _obj


