# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from solifyn.models.meter_usage_event_dto import MeterUsageEventDto
from typing import Optional, Set
from typing_extensions import Self

class MeterDetailResponseDto(BaseModel):
    """
    Represents a usage meter with its most recent usage events and total usage event count.
    """ # noqa: E501
    id: StrictStr = Field(description="The unique meter ID.")
    business_id: StrictStr = Field(description="The business ID that owns this meter.", alias="businessId")
    name: StrictStr = Field(description="Meter display name.")
    description: Optional[Dict[str, Any]] = Field(default=None, description="Meter description.")
    event_name: StrictStr = Field(description="The event name tracked by this meter.", alias="eventName")
    aggregation_type: StrictStr = Field(description="Aggregation strategy for usage events.", alias="aggregationType")
    aggregation_key: Optional[Dict[str, Any]] = Field(default=None, description="Metadata key used for aggregation.", alias="aggregationKey")
    unit: Optional[Dict[str, Any]] = Field(default=None, description="Measurement unit label.")
    filters: Optional[Dict[str, Any]] = Field(default=None, description="Optional filter definition for advanced matching.")
    archived: StrictBool = Field(description="Whether the meter is archived.")
    created_at: datetime = Field(description="Creation timestamp.", alias="createdAt")
    updated_at: datetime = Field(description="Last update timestamp.", alias="updatedAt")
    usage_events: List[MeterUsageEventDto] = Field(description="Most recent usage events recorded for the meter.", alias="usageEvents")
    total_usage_events: Union[StrictFloat, StrictInt] = Field(description="Total usage event count for the meter.", alias="totalUsageEvents")
    __properties: ClassVar[List[str]] = ["id", "businessId", "name", "description", "eventName", "aggregationType", "aggregationKey", "unit", "filters", "archived", "createdAt", "updatedAt", "usageEvents", "totalUsageEvents"]

    @field_validator('aggregation_type')
    def aggregation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['COUNT', 'SUM', 'MAX', 'LAST']):
            raise ValueError("must be one of enum values ('COUNT', 'SUM', 'MAX', 'LAST')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeterDetailResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in usage_events (list)
        _items = []
        if self.usage_events:
            for _item_usage_events in self.usage_events:
                if _item_usage_events:
                    _items.append(_item_usage_events.to_dict())
            _dict['usageEvents'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeterDetailResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "businessId": obj.get("businessId"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "eventName": obj.get("eventName"),
            "aggregationType": obj.get("aggregationType"),
            "aggregationKey": obj.get("aggregationKey"),
            "unit": obj.get("unit"),
            "filters": obj.get("filters"),
            "archived": obj.get("archived"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "usageEvents": [MeterUsageEventDto.from_dict(_item) for _item in obj["usageEvents"]] if obj.get("usageEvents") is not None else None,
            "totalUsageEvents": obj.get("totalUsageEvents")
        })
        return _obj


