# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from solifyn.models.order_billing import OrderBilling
from solifyn.models.order_customer import OrderCustomer
from solifyn.models.order_detail import OrderDetail
from solifyn.models.order_product_cart import OrderProductCart
from solifyn.models.order_refund import OrderRefund
from typing import Optional, Set
from typing_extensions import Self

class Order(BaseModel):
    """
    Represents an order (payment) processed under your business, containing customer, billing, product cart, and refund details.
    """ # noqa: E501
    id: StrictStr = Field(description="Unique internal database identifier.")
    invoice_url: StrictStr = Field(description="The invoice print URL.")
    customer: OrderCustomer = Field(description="Customer details.")
    total_amount: StrictInt = Field(description="Total paid amount in cents.")
    subtotal: StrictInt = Field(description="Subtotal amount in cents.")
    tax_amount: StrictInt = Field(description="Tax amount in cents.")
    application_fee: StrictInt = Field(description="Application fee in cents.")
    amount_after_fees: StrictInt = Field(description="Net amount after fees in cents.")
    currency: StrictStr = Field(description="Currency code.")
    status: StrictStr = Field(description="Current status of the payment.")
    created_at: datetime = Field(description="Payment creation timestamp.")
    paid_at: Optional[datetime] = Field(default=None, description="Payment completion/paid timestamp.", alias="paidAt")
    payment_method: StrictStr = Field(description="Payment method utilized.")
    card_last_four: Optional[StrictStr] = Field(default=None, description="Last four digits of card used.")
    card_network: Optional[StrictStr] = Field(default=None, description="Card network/brand.")
    card_type: Optional[StrictStr] = Field(default=None, description="Card type.")
    billing: Optional[OrderBilling] = Field(default=None, description="Billing address details.")
    product_cart: List[OrderProductCart] = Field(description="Products purchased in this order.")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Custom metadata payload associated with this payment.")
    order: Optional[OrderDetail] = Field(default=None, description="Order details snapshot.")
    refundable: StrictBool = Field(description="Indicates whether the order is eligible for refund.")
    refunds: Optional[List[OrderRefund]] = Field(default=None, description="List of refunds associated with this payment.")
    business_id: StrictStr = Field(description="Business unique ID identifier.", alias="businessId")
    business_name: StrictStr = Field(description="Business display title/name.", alias="businessName")
    billing_reason: Optional[StrictStr] = Field(default=None, description="Billing reason detail.")
    __properties: ClassVar[List[str]] = ["id", "invoice_url", "customer", "total_amount", "subtotal", "tax_amount", "application_fee", "amount_after_fees", "currency", "status", "created_at", "paidAt", "payment_method", "card_last_four", "card_network", "card_type", "billing", "product_cart", "metadata", "order", "refundable", "refunds", "businessId", "businessName", "billing_reason"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Order from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of billing
        if self.billing:
            _dict['billing'] = self.billing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in product_cart (list)
        _items = []
        if self.product_cart:
            for _item_product_cart in self.product_cart:
                if _item_product_cart:
                    _items.append(_item_product_cart.to_dict())
            _dict['product_cart'] = _items
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict['order'] = self.order.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in refunds (list)
        _items = []
        if self.refunds:
            for _item_refunds in self.refunds:
                if _item_refunds:
                    _items.append(_item_refunds.to_dict())
            _dict['refunds'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Order from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "invoice_url": obj.get("invoice_url"),
            "customer": OrderCustomer.from_dict(obj["customer"]) if obj.get("customer") is not None else None,
            "total_amount": obj.get("total_amount"),
            "subtotal": obj.get("subtotal"),
            "tax_amount": obj.get("tax_amount"),
            "application_fee": obj.get("application_fee"),
            "amount_after_fees": obj.get("amount_after_fees"),
            "currency": obj.get("currency"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "paidAt": obj.get("paidAt"),
            "payment_method": obj.get("payment_method"),
            "card_last_four": obj.get("card_last_four"),
            "card_network": obj.get("card_network"),
            "card_type": obj.get("card_type"),
            "billing": OrderBilling.from_dict(obj["billing"]) if obj.get("billing") is not None else None,
            "product_cart": [OrderProductCart.from_dict(_item) for _item in obj["product_cart"]] if obj.get("product_cart") is not None else None,
            "metadata": obj.get("metadata"),
            "order": OrderDetail.from_dict(obj["order"]) if obj.get("order") is not None else None,
            "refundable": obj.get("refundable"),
            "refunds": [OrderRefund.from_dict(_item) for _item in obj["refunds"]] if obj.get("refunds") is not None else None,
            "businessId": obj.get("businessId"),
            "businessName": obj.get("businessName"),
            "billing_reason": obj.get("billing_reason")
        })
        return _obj


