# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from solifyn.models.subscription_company_dto import SubscriptionCompanyDto
from solifyn.models.subscription_member_dto import SubscriptionMemberDto
from solifyn.models.subscription_plan_dto import SubscriptionPlanDto
from solifyn.models.subscription_product_dto import SubscriptionProductDto
from solifyn.models.subscription_user_dto import SubscriptionUserDto
from typing import Optional, Set
from typing_extensions import Self

class Subscription(BaseModel):
    """
    Represents a customer subscription membership resource, containing current billing terms, plan, status, and metadata.
    """ # noqa: E501
    id: StrictStr = Field(description="The unique ID of the subscription")
    status: StrictStr = Field(description="The status of the subscription (e.g. completed, active, trialing, past_due, canceled)")
    created_at: datetime = Field(description="Timestamp when the subscription was created")
    joined_at: datetime = Field(description="Timestamp when the member joined")
    updated_at: datetime = Field(description="Timestamp when the subscription was last updated")
    manage_url: StrictStr = Field(description="The management URL for the billing/subscription")
    member: SubscriptionMemberDto = Field(description="The member details")
    user: SubscriptionUserDto = Field(description="The user details")
    renewal_period_start: Optional[Dict[str, Any]] = Field(description="Start timestamp of the current renewal period")
    renewal_period_end: Optional[Dict[str, Any]] = Field(description="End timestamp of the current renewal period")
    cancel_at_period_end: StrictBool = Field(description="Whether the subscription is set to cancel at the end of the billing period")
    cancel_option: Optional[Dict[str, Any]] = Field(description="The cancel option details")
    cancellation_reason: Optional[Dict[str, Any]] = Field(description="The reason for cancellation")
    canceled_at: Optional[Dict[str, Any]] = Field(description="Timestamp when the subscription was canceled")
    currency: StrictStr = Field(description="The currency used for payments")
    company: SubscriptionCompanyDto = Field(description="The company context details")
    plan: SubscriptionPlanDto = Field(description="The plan associated with this subscription")
    promo_code: Optional[Dict[str, Any]] = Field(description="The promo code applied to the subscription")
    product: SubscriptionProductDto = Field(description="The product associated with the subscription")
    license_key: Optional[Dict[str, Any]] = Field(description="The license key associated with this subscription")
    metadata: Dict[str, Any] = Field(description="Additional metadata for the subscription")
    payment_collection_paused: StrictBool = Field(description="Whether the payment collection is currently paused")
    checkout_configuration_id: StrictStr = Field(description="The checkout configuration ID used")
    price: Optional[Dict[str, Any]] = Field(default=None, description="The price/amount of the membership")
    type: Optional[Dict[str, Any]] = Field(default=None, description="The type of the membership plan")
    customer_id: Optional[Dict[str, Any]] = Field(default=None, description="The business customer ID", alias="customerId")
    __properties: ClassVar[List[str]] = ["id", "status", "created_at", "joined_at", "updated_at", "manage_url", "member", "user", "renewal_period_start", "renewal_period_end", "cancel_at_period_end", "cancel_option", "cancellation_reason", "canceled_at", "currency", "company", "plan", "promo_code", "product", "license_key", "metadata", "payment_collection_paused", "checkout_configuration_id", "price", "type", "customerId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Subscription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of member
        if self.member:
            _dict['member'] = self.member.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of company
        if self.company:
            _dict['company'] = self.company.to_dict()
        # override the default output from pydantic by calling `to_dict()` of plan
        if self.plan:
            _dict['plan'] = self.plan.to_dict()
        # override the default output from pydantic by calling `to_dict()` of product
        if self.product:
            _dict['product'] = self.product.to_dict()
        # set to None if renewal_period_start (nullable) is None
        # and model_fields_set contains the field
        if self.renewal_period_start is None and "renewal_period_start" in self.model_fields_set:
            _dict['renewal_period_start'] = None

        # set to None if renewal_period_end (nullable) is None
        # and model_fields_set contains the field
        if self.renewal_period_end is None and "renewal_period_end" in self.model_fields_set:
            _dict['renewal_period_end'] = None

        # set to None if cancel_option (nullable) is None
        # and model_fields_set contains the field
        if self.cancel_option is None and "cancel_option" in self.model_fields_set:
            _dict['cancel_option'] = None

        # set to None if cancellation_reason (nullable) is None
        # and model_fields_set contains the field
        if self.cancellation_reason is None and "cancellation_reason" in self.model_fields_set:
            _dict['cancellation_reason'] = None

        # set to None if canceled_at (nullable) is None
        # and model_fields_set contains the field
        if self.canceled_at is None and "canceled_at" in self.model_fields_set:
            _dict['canceled_at'] = None

        # set to None if promo_code (nullable) is None
        # and model_fields_set contains the field
        if self.promo_code is None and "promo_code" in self.model_fields_set:
            _dict['promo_code'] = None

        # set to None if license_key (nullable) is None
        # and model_fields_set contains the field
        if self.license_key is None and "license_key" in self.model_fields_set:
            _dict['license_key'] = None

        # set to None if price (nullable) is None
        # and model_fields_set contains the field
        if self.price is None and "price" in self.model_fields_set:
            _dict['price'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if customer_id (nullable) is None
        # and model_fields_set contains the field
        if self.customer_id is None and "customer_id" in self.model_fields_set:
            _dict['customerId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Subscription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "joined_at": obj.get("joined_at"),
            "updated_at": obj.get("updated_at"),
            "manage_url": obj.get("manage_url"),
            "member": SubscriptionMemberDto.from_dict(obj["member"]) if obj.get("member") is not None else None,
            "user": SubscriptionUserDto.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "renewal_period_start": obj.get("renewal_period_start"),
            "renewal_period_end": obj.get("renewal_period_end"),
            "cancel_at_period_end": obj.get("cancel_at_period_end"),
            "cancel_option": obj.get("cancel_option"),
            "cancellation_reason": obj.get("cancellation_reason"),
            "canceled_at": obj.get("canceled_at"),
            "currency": obj.get("currency"),
            "company": SubscriptionCompanyDto.from_dict(obj["company"]) if obj.get("company") is not None else None,
            "plan": SubscriptionPlanDto.from_dict(obj["plan"]) if obj.get("plan") is not None else None,
            "promo_code": obj.get("promo_code"),
            "product": SubscriptionProductDto.from_dict(obj["product"]) if obj.get("product") is not None else None,
            "license_key": obj.get("license_key"),
            "metadata": obj.get("metadata"),
            "payment_collection_paused": obj.get("payment_collection_paused"),
            "checkout_configuration_id": obj.get("checkout_configuration_id"),
            "price": obj.get("price"),
            "type": obj.get("type"),
            "customerId": obj.get("customerId")
        })
        return _obj


