# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SubscriptionAction(BaseModel):
    """
    SubscriptionAction
    """ # noqa: E501
    free_days: Optional[Union[Annotated[float, Field(le=3650, strict=True, ge=1)], Annotated[int, Field(le=3650, strict=True, ge=1)]]] = Field(default=None, description="Number of free days to add (used with action: add_free_days)")
    cancellation_mode: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="Cancellation mode (used with action: cancel)")
    void_payments: Optional[StrictBool] = Field(default=None, description="Whether to void subsequent payments (used with action: pause)")
    addon_product_id: Optional[StrictStr] = Field(default=None, description="ID of the addon product to adjust seats for (used with action: adjust_seats)", alias="addonProductId")
    new_quantity: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="The new seat quantity (used with action: adjust_seats)", alias="newQuantity")
    proration_type: Optional[StrictStr] = Field(default=None, description="Proration strategy mode (used with action: adjust_seats)", alias="prorationType")
    idempotency_key: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="A unique idempotency key to prevent duplicate mutative actions for network transient retries.", alias="idempotencyKey")
    __properties: ClassVar[List[str]] = ["free_days", "cancellation_mode", "void_payments", "addonProductId", "newQuantity", "prorationType", "idempotencyKey"]

    @field_validator('cancellation_mode')
    def cancellation_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['immediate', 'at_period_end']):
            raise ValueError("must be one of enum values ('immediate', 'at_period_end')")
        return value

    @field_validator('proration_type')
    def proration_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['prorated_immediately', 'full_immediately', 'difference_immediately', 'do_not_bill']):
            raise ValueError("must be one of enum values ('prorated_immediately', 'full_immediately', 'difference_immediately', 'do_not_bill')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionAction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "free_days": obj.get("free_days"),
            "cancellation_mode": obj.get("cancellation_mode"),
            "void_payments": obj.get("void_payments"),
            "addonProductId": obj.get("addonProductId"),
            "newQuantity": obj.get("newQuantity"),
            "prorationType": obj.get("prorationType"),
            "idempotencyKey": obj.get("idempotencyKey")
        })
        return _obj


