# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UpdateMeterDto(BaseModel):
    """
    UpdateMeterDto
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Meter display name.")
    description: Optional[StrictStr] = Field(default=None, description="Meter description.")
    event_name: Optional[StrictStr] = Field(default=None, description="The event name tracked by this meter.", alias="eventName")
    aggregation_type: Optional[StrictStr] = Field(default=None, description="Aggregation strategy for usage events.", alias="aggregationType")
    aggregation_key: Optional[StrictStr] = Field(default=None, description="Metadata key used by SUM, MAX, or LAST aggregation modes.", alias="aggregationKey")
    unit: Optional[StrictStr] = Field(default=None, description="Measurement unit label.")
    filters: Optional[Dict[str, Any]] = Field(default=None, description="Optional filter definition for advanced matching.")
    enable_filtering: Optional[StrictBool] = Field(default=None, description="Enable filtering on usage event ingestion.", alias="enableFiltering")
    __properties: ClassVar[List[str]] = ["name", "description", "eventName", "aggregationType", "aggregationKey", "unit", "filters", "enableFiltering"]

    @field_validator('aggregation_type')
    def aggregation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['COUNT', 'SUM', 'MAX', 'LAST']):
            raise ValueError("must be one of enum values ('COUNT', 'SUM', 'MAX', 'LAST')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateMeterDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateMeterDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "eventName": obj.get("eventName"),
            "aggregationType": obj.get("aggregationType"),
            "aggregationKey": obj.get("aggregationKey"),
            "unit": obj.get("unit"),
            "filters": obj.get("filters"),
            "enableFiltering": obj.get("enableFiltering")
        })
        return _obj


