# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WebhookEntitlementGrantPayload(BaseModel):
    """
    WebhookEntitlementGrantPayload
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="The unique entitlement grant ID.")
    business_id: Optional[StrictStr] = Field(default=None, description="The business ID context.", alias="businessId")
    customer_id: Optional[StrictStr] = Field(default=None, description="The customer ID.", alias="customerId")
    payment_id: Optional[StrictStr] = Field(default=None, description="Associated payment transaction ID.", alias="paymentId")
    product_id: Optional[StrictStr] = Field(default=None, description="The purchased product ID.", alias="productId")
    type: Optional[StrictStr] = Field(default=None, description="The type of entitlement (e.g. GITHUB).")
    github_repo: Optional[StrictStr] = Field(default=None, description="Target GitHub repository (owner/repo) if type is GITHUB.", alias="githubRepo")
    github_permission: Optional[StrictStr] = Field(default=None, description="GitHub access permission level if type is GITHUB.", alias="githubPermission")
    github_username: Optional[StrictStr] = Field(default=None, description="The connected customer GitHub username.", alias="githubUsername")
    status: Optional[StrictStr] = Field(default=None, description="Delivery status of the collaborator invite (PENDING, DELIVERED, FAILED, REVOKED).")
    oauth_url: Optional[StrictStr] = Field(default=None, description="OAuth URL to redirect the customer to.", alias="oauthUrl")
    error_details: Optional[StrictStr] = Field(default=None, description="Error message if invitation delivery failed.", alias="errorDetails")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "businessId", "customerId", "paymentId", "productId", "type", "githubRepo", "githubPermission", "githubUsername", "status", "oauthUrl", "errorDetails", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookEntitlementGrantPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookEntitlementGrantPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "businessId": obj.get("businessId"),
            "customerId": obj.get("customerId"),
            "paymentId": obj.get("paymentId"),
            "productId": obj.get("productId"),
            "type": obj.get("type"),
            "githubRepo": obj.get("githubRepo"),
            "githubPermission": obj.get("githubPermission"),
            "githubUsername": obj.get("githubUsername"),
            "status": obj.get("status"),
            "oauthUrl": obj.get("oauthUrl"),
            "errorDetails": obj.get("errorDetails"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


