# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WebhookDisputePayload(BaseModel):
    """
    WebhookDisputePayload
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Internal dispute ID.")
    payment_id: Optional[StrictStr] = Field(default=None, alias="paymentId")
    amount: Optional[StrictStr] = Field(default=None, description="Dollar value, 2 d.p.")
    currency: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    reason: Optional[StrictStr] = None
    editable: Optional[StrictBool] = None
    needs_response_by: Optional[datetime] = Field(default=None, alias="needsResponseBy")
    customer_name: Optional[StrictStr] = Field(default=None, alias="customerName")
    customer_email: Optional[StrictStr] = Field(default=None, alias="customerEmail")
    notes: Optional[StrictStr] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "paymentId", "amount", "currency", "status", "reason", "editable", "needsResponseBy", "customerName", "customerEmail", "notes", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookDisputePayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookDisputePayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "paymentId": obj.get("paymentId"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "status": obj.get("status"),
            "reason": obj.get("reason"),
            "editable": obj.get("editable"),
            "needsResponseBy": obj.get("needsResponseBy"),
            "customerName": obj.get("customerName"),
            "customerEmail": obj.get("customerEmail"),
            "notes": obj.get("notes"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


