# coding: utf-8

"""
    Solifyn API

    Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

    The version of the OpenAPI document: 1.0.0
    Contact: support@solifyn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Withdrawal(BaseModel):
    """
    Withdrawal
    """ # noqa: E501
    id: StrictStr = Field(description="The local withdrawal ID")
    whop_id: StrictStr = Field(description="The Whop withdrawal ID", alias="whopId")
    amount: Union[StrictFloat, StrictInt] = Field(description="The amount withdrawn in cents")
    currency: StrictStr = Field(description="Three-letter ISO currency code")
    status: StrictStr = Field(description="The status of the withdrawal request")
    fee_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Fee amount charged for the withdrawal in cents", alias="feeAmount")
    fee_type: Optional[StrictStr] = Field(default=None, description="The fee structure type (inclusive or exclusive)", alias="feeType")
    markup_fee: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Markup fee applied in cents", alias="markupFee")
    speed: Optional[StrictStr] = Field(default=None, description="Speed of withdrawal (standard, instant)")
    trace_code: Optional[StrictStr] = Field(default=None, description="Bank trace or reference code for tracking the payout", alias="traceCode")
    payer_name: Optional[StrictStr] = Field(default=None, description="The name of the entity or account paying out", alias="payerName")
    error_message: Optional[StrictStr] = Field(default=None, description="Error message if the withdrawal failed", alias="errorMessage")
    business_id: StrictStr = Field(description="The business ID associated with this withdrawal", alias="businessId")
    created_at: datetime = Field(description="Timestamp when the withdrawal was requested", alias="createdAt")
    updated_at: datetime = Field(description="Timestamp when the withdrawal status was updated", alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "whopId", "amount", "currency", "status", "feeAmount", "feeType", "markupFee", "speed", "traceCode", "payerName", "errorMessage", "businessId", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Withdrawal from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Withdrawal from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "whopId": obj.get("whopId"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "status": obj.get("status"),
            "feeAmount": obj.get("feeAmount"),
            "feeType": obj.get("feeType"),
            "markupFee": obj.get("markupFee"),
            "speed": obj.get("speed"),
            "traceCode": obj.get("traceCode"),
            "payerName": obj.get("payerName"),
            "errorMessage": obj.get("errorMessage"),
            "businessId": obj.get("businessId"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


